
-- CREATE TABLE items (
--   id int generated always as identity,
--   publish_date date,
--   archived boolean,
--   genre_id int,
--   author_id int,
--   label_id int,
--   PRIMARY KEY (id)
-- )

CREATE TABLE items (
  id SERIAL PRIMARY KEY,
  genre_id INTEGER REFERENCES genres(id),
  author_id INTEGER REFERENCES authors(id),
  label_id INTEGER REFERENCES labels(id),
  publish_date DATE NOT NULL,
  archived BOOLEAN NOT NULL
);

-- for book

CREATE TABLE books (
  id INTEGER PRIMARY KEY REFERENCES items(id),
  publisher VARCHAR(255) NOT NULL,
  cover_state VARCHAR(255) NOT NULL
);

-- for label

CREATE TABLE labels (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  color VARCHAR(255) NOT NULL
);


-- foreign key index
CREATE INDEX items_label_id_idx ON items (label_id);

CREATE TABLE games (
  item_id int,
  multiplayer boolean,
  last_played_at date,
  PRIMARY KEY (item_id)
);

CREATE TABLE authors (
  id int generated by default as identity,
  first_name varchar,
  last_name varchar,
  PRIMARY KEY (id)
);

CREATE TABLE genres (
  id int generated by default as identity,
  name varchar,
  PRIMARY KEY (id)
);

CREATE TABLE music_albums (
  id int generated by default as identity,
  publish_date date,
  on_spotify boolean,
  item_id FOREIGN KEY REFERENCES items(id),
  PRIMARY KEY(id)
);

