
CREATE TABLE items (
  id int generated by default as identity,
  publish_date date,
  archived boolean,
  genre_id int,
  author_id int,
  label_id int,
  PRIMARY KEY (id)
)

CREATE TABLE games (
  item_id int,
  multiplayer boolean,
  last_played_at date,
  PRIMARY KEY (item_id)
);

CREATE TABLE authors (
  id int generated by default as identity,
  first_name varchar,
  last_name varchar,
  PRIMARY KEY (id)
);
