CREATE TABLE items (
  id SERIAL PRIMARY KEY,
  genre_id INTEGER REFERENCES genres(id),
  author_id INTEGER REFERENCES authors(id),
  label_id INTEGER REFERENCES labels(id),
  publish_date DATE NOT NULL,
  archived BOOLEAN NOT NULL
);

CREATE TABLE labels (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  color VARCHAR(255) NOT NULL
);

CREATE TABLE authors (
  id int generated by default as identity,
  first_name varchar,
  last_name varchar,
  PRIMARY KEY (id)
);

CREATE TABLE genres (
  id int generated by default as identity,
  name varchar,
  PRIMARY KEY (id)
);

-- foreign key index
CREATE INDEX items_label_id_idx ON items (label_id);

CREATE TABLE books (
  id INTEGER PRIMARY KEY REFERENCES items(id),
  publisher VARCHAR(255) NOT NULL,
  cover_state VARCHAR(255) NOT NULL
);

CREATE TABLE games (
  item_id int,
  multiplayer boolean,
  last_played_at date,
  PRIMARY KEY (item_id)
);

CREATE TABLE music_albums (
  id int generated by default as identity,
  publish_date date,
  on_spotify boolean,
  PRIMARY KEY(id)
);

